route:
  receiver: 'email'
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h

receivers:
  - name: 'email'
    email_configs:
      - to: 'admin@sume.one'
        from: 'info@sume.one'
        smarthost: 'mail.privateemail.com:587'
        auth_username: 'hi@sume.one'
        auth_password: 'M@nKHARAM5589'
        headers:
          Subject: 'SigNoz Alert: {{ .GroupLabels.alertname }}'