
x-clickhouse-defaults: &clickhouse-defaults
  image: clickhouse/clickhouse-server:25.5.6
  restart: unless-stopped
  tty: true
  healthcheck:
    test: ["CMD", "wget", "--spider", "-q", "0.0.0.0:8123/ping"]
    interval: 30s
    timeout: 5s
    retries: 3
  ulimits:
    nproc: 65535
    nofile:
      soft: 262144
      hard: 262144

services:
  zookeeper:
    image: zookeeper:3.9
    restart: unless-stopped
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=0.0.0.0:2888:3888;2181
    volumes:
      - zookeeper_data:/data
    healthcheck:
      test: ["CMD-SHELL", "echo ruok | nc localhost 2181 | grep imok"]
      interval: 10s
      timeout: 5s
      retries: 5

  clickhouse:
    <<: *clickhouse-defaults
    container_name: signoz-clickhouse
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9000:9000"
      - "8123:8123"

  query-service:
    image: signoz/query-service:0.63.0
    restart: unless-stopped
    command: ["-config=/root/config/prometheus.yml"]
    environment:
      - ClickHouseUrl=tcp://clickhouse:9000
      - ALERTMANAGER_API_PREFIX=http://alertmanager:9093/api/
      - SIGNOZ_LOCAL_DB_PATH=/var/lib/signoz/signoz.db
      - DASHBOARDS_PATH=/root/config/dashboards
      - STORAGE=clickhouse
      - GODEBUG=netdns=go
      - TELEMETRY_ENABLED=true
      - DEPLOYMENT_TYPE=docker-standalone-amd
    volumes:
      - signoz_data:/var/lib/signoz
    depends_on:
      clickhouse:
        condition: service_healthy

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.102.0
    restart: unless-stopped
    command: ["--config=/etc/otel-collector-config.yaml"]
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=host.name=signoz-host,os.type=linux
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
    depends_on:
      clickhouse:
        condition: service_healthy

  frontend:
    image: signoz/frontend:0.63.0
    restart: unless-stopped
    environment:
      - FRONTEND_API_ENDPOINT=http://query-service:8080
    ports:
      - "3301:3301"
    depends_on:
      - query-service

  alertmanager:
    image: signoz/alertmanager:0.23.5
    restart: unless-stopped
    volumes:
      - ./alertmanager-config.yml:/etc/alertmanager/config.yml
    command:
      - --queryURL=http://query-service:8080
      - --config.file=/etc/alertmanager/config.yml
    ports:
      - "9093:9093"

volumes:
  clickhouse_data:
  zookeeper_data:
  signoz_data: